n=int(input('digite um numero:'))
print(f'tabuada')
print('-'*12)
print (n,f'x 0= 0')
print (n,f'x 1= {n*1}')
print (n,f'x 2= {n*2}')
print (n,f'x 3= {n*3}')
print (n,f'x 4= {n*4}')
print (n,f'x 5= {n*5}')
print (n,f'x 6= {n*6}')
print (n,f'x 7= {n*7}')
print (n,f'x 8= {n*8}')
print (n,f'x 9= {n*9}')
print (n,f'x 10= {n*10}')
print('-'*12)
